### ISSUE TITLE
Docs pls!!

### ISSUE THREAD

**Issue by tobioyelekan** [AndroidDeveloperLB/VideoTrimmer#12]

**Comment by AndroidDeveloperLB** [comment]
Already on the repository that it's based on:
https://github.com/titansgroup/k4l-video-trimmer

**Comment by maphongba008** [comment]
Can't find the TrimmerView like this
```
<life.knowledge4.videotrimmer.K4LVideoTrimmer
    android:id="@+id/timeLine"
    android:layout_height="match_parent"
    android:layout_width="match_parent" />
```
Does it take much time to write a simple usage of the project?

**Comment by AndroidDeveloperLB** [comment]
It's not my project. I only forked an existing one. I've updated the main page to explain it, again.
