### ISSUE TITLE
Need for the print stack trace

### ISSUE THREAD

**Issue by kerimovscreations** [AndroidDeveloperLB/VideoTrimmer#14]
Thanks for the library. I got the fatal error while implementation, but can't debug it. There was not any log in the console log. After pulling the library itself and adding `e.printStackTrace();`  in the `onSaveClicked()` method I got a real reason for my bug.
The bug was: methods of the `OnTrimVideoListener` calling in the background thread and I accessed UI component in the callback.
I suggest you add printStackTrace line in the `K4LVideoTrimmer.class`

**Comment by AndroidDeveloperLB** [comment]
Feel free to fork and help contributing to the project.
