### ISSUE TITLE
change output size to reduce file size 

### ISSUE THREAD

**Issue by yesidlazaro** [AndroidDeveloperLB/VideoTrimmer#2]
hi, do you know how to change the output video size, for example 640x480 as a maximum size ? thanks in advance and great project by the way

**Comment by AndroidDeveloperLB** [comment]
Sorry no idea. I only forked this to make a nicer trimmer...
Ask on StackOverflow, and write here about it. I will follow :)

**Comment by yesidlazaro** [comment]
hi, thanks for your response, i will ask on StackOverflow.

**Comment by AndroidDeveloperLB** [comment]
Please keep me informed with a link to what you made.
