### ISSUE TITLE
How to get max duration of video

### ISSUE THREAD

**Issue by majidalik** [AndroidDeveloperLB/VideoTrimmer#7]
How can i get maxDurationInMs of attached video since maxDurationInMs variable is private.

My view class is extends BaseVideoTrimmerView and I have added blow library in build.gradle. 
implementation 'com.github.AndroidDeveloperLB:VideoTrimmer:5'

**Comment by AndroidDeveloperLB** [comment]
In which class exactly?
If you wish, you can fork and do a pull request with this change. I don't see why not provide such a thing.
The code is based on another project, so I didn't handle everything. I just made it a bit better and more updated.
