### ISSUE TITLE
How I can I use this library for Java codes?

### ISSUE THREAD

**Issue by akkisjoy** [AndroidDeveloperLB/VideoTrimmer#8]
This is very great work done by you, but since this is in kotlin and my existing project in Java, which I can not modify to kotlin for now. How I can utilise there?

**Comment by AndroidDeveloperLB** [comment]
Kotlin is what Google goes today. All documentation now defaults to Kotlin, and when you create a new project on the IDE it's on Kotlin by default.
Learning Kotlin is important, and it's very similar to Java anyway.

You can use this library from Java code if you wish. It works fine.
